<?php
/**
 * Initialize the custom theme options.
 */
add_action( 'admin_init', 'mnky_custom_theme_options' );

/**
 * Build the custom settings & update OptionTree.
 */
function mnky_custom_theme_options() {
  
  /* OptionTree is not loaded yet */
  if ( ! function_exists( 'ot_settings_id' ) )
    return false;
    
  /**
   * Get a copy of the saved settings array. 
   */
  $saved_settings = get_option( ot_settings_id(), array() );
  
  /**
   * Custom settings array that will eventually be 
   * passes to the OptionTree Settings API Class.
   */
  $custom_settings = array( 
    'contextual_help' => array( 
      'sidebar'       => ''
    ),
    'sections'        => array( 
      array(
        'id'          => 'general',
        'title'       => __( 'General Options', 'quince' )
      ),
      array(
        'id'          => 'header_options',
        'title'       => __( 'Header', 'quince' )
      ),
      array(
        'id'          => 'title_options',
        'title'       => __( 'Title Area', 'quince' )
      ),
      array(
        'id'          => 'color_options',
        'title'       => __( 'Content Colors', 'quince' )
      ),
      array(
        'id'          => 'typography',
        'title'       => __( 'Typography', 'quince' )
      ),
      array(
        'id'          => 'footer_options',
        'title'       => __( 'Footer', 'quince' )
      ),
      array(
        'id'          => 'blog_options',
        'title'       => __( 'Blog &amp; Posts', 'quince' )
      ),
      array(
        'id'          => 'woocommerce',
        'title'       => __( 'WooCommerce', 'quince' )
      ),
      array(
        'id'          => 'custom_css',
        'title'       => __( 'Custom CSS', 'quince' )
      ),
      array(
        'id'          => 'import_data',
        'title'       => __( 'Import Demo', 'quince' )
      ),
      array(
        'id'          => 'import_successful',
        'title'       => __( 'Import Successful', 'quince' )
      )
    ),
    'settings'        => array( 
      array(
        'id'          => 'primary_tab',
        'label'       => __( 'Primary', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'accent_color',
        'label'       => __( 'Theme accent color', 'quince' ),
        'desc'        => __( 'This will be general color scheme for your website. Click input field for color picker.', 'quince' ),
        'std'         => '#8fc941',
        'type'        => 'colorpicker',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'layout_style',
        'label'       => __( 'Layout style', 'quince' ),
        'desc'        => __( '1. Full width layout <br />
2. Boxed layout', 'quince' ),
        'std'         => 'full-width',
        'type'        => 'radio-image',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'header_style',
        'label'       => __( 'Header width', 'quince' ),
        'desc'        => __( 'For full width layout you can chose from 2 header styles:<br />
1. Full width<br />
2. Same as content width', 'quince' ),
        'std'         => 'fixed-width',
        'type'        => 'radio-image',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'layout_style:is(full-width)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'content_width',
        'label'       => __( 'Content width', 'quince' ),
        'desc'        => __( 'This setting will apply selected layout width to your website.', 'quince' ),
        'std'         => '1100',
        'type'        => 'radio',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array( 
          array(
            'value'       => '940',
            'label'       => __( '940px', 'quince' ),
            'src'         => ''
          ),
          array(
            'value'       => '980',
            'label'       => __( '980px', 'quince' ),
            'src'         => ''
          ),
          array(
            'value'       => '1100',
            'label'       => __( '1100px', 'quince' ),
            'src'         => ''
          )
        )
      ),
      array(
        'id'          => 'scroll_to_top_button',
        'label'       => __( 'Scroll to top button', 'quince' ),
        'desc'        => __( 'Enable or disable "To Top" button when you scroll down.', 'quince' ),
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'page_comments',
        'label'       => __( 'Comments on page', 'quince' ),
        'desc'        => __( 'Turn ON or OFF comments on pages.', 'quince' ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'body_background',
        'label'       => __( 'Body background', 'quince' ),
        'desc'        => __( 'Choose body background for boxed layout.', 'quince' ),
        'std'         => '',
        'type'        => 'background',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'layout_style:is(boxed)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'use_pattern',
        'label'       => __( 'Predefined pattern', 'quince' ),
        'desc'        => __( 'Select background pattern for boxed layout.', 'quince' ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'layout_style:is(boxed)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'background_pattern',
        'label'       => __( 'Patterns', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'radio-image',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'layout_style:is(boxed),use_pattern:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'favicon_tab',
        'label'       => __( 'Favicons', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'favicon',
        'label'       => __( 'Favicon', 'quince' ),
        'desc'        => __( 'Size 16x16 px. Upload image in .ico format.', 'quince' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'iphone_favicon',
        'label'       => __( 'iPhone icon', 'quince' ),
        'desc'        => __( 'If set, anyone who saves your webpage to the home screen will see a nice app-like icon. <br />
Recommended image format is .png. <br />
Size 60x60 px.', 'quince' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'iphone_favicon_retina',
        'label'       => __( 'iPhone retina icon', 'quince' ),
        'desc'        => __( 'Size 120x120 px.', 'quince' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'ipad_favicon',
        'label'       => __( 'iPad icon', 'quince' ),
        'desc'        => __( 'Size 76x76 px.', 'quince' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'ipad_favicon_retina',
        'label'       => __( 'iPad retina icon', 'quince' ),
        'desc'        => __( 'Size 152x152 px.', 'quince' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'code_tab',
        'label'       => __( 'Analytics &amp; Custom code', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'tracking_code',
        'label'       => __( 'Analytics / tracking code', 'quince' ),
        'desc'        => __( 'Paste your Google Analytics or other tracking code in text area. Or any code to be placed before <code><span>&lt;</span>/head&gt;</code> in header file.', 'quince' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'general',
        'rows'        => '10',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'code_before_body',
        'label'       => __( 'Code before <span>&lt;</span>/body&gt;', 'quince' ),
        'desc'        => __( 'Add your custom code in footer before <code><span>&lt;</span>/body&gt;</code> tag.', 'quince' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'general',
        'rows'        => '10',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'default_header_tab',
        'label'       => __( 'General', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'sticky_header',
        'label'       => __( 'Sticky header', 'quince' ),
        'desc'        => __( 'Do you want a header to stick to top while you scroll?', 'quince' ),
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'header_height',
        'label'       => __( 'Header height', 'quince' ),
        'desc'        => __( 'Height of the header area (menu area). Example: <code>65px</code>', 'quince' ),
        'std'         => '90px',
        'type'        => 'text',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'header_bg',
        'label'       => __( 'Header background color', 'quince' ),
        'desc'        => __( 'Choose your site header color.', 'quince' ),
        'std'         => '#414856',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'menu_tab',
        'label'       => __( 'Menu', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'search_button',
        'label'       => __( 'Search button in menu', 'quince' ),
        'desc'        => __( 'Enables or disables search from menu.', 'quince' ),
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'cart_button',
        'label'       => __( 'WooCommerce cart button in menu', 'quince' ),
        'desc'        => __( 'Do you want a smart WooCommerce cart icon in main menu?', 'quince' ),
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'menu_right',
        'label'       => __( 'Menu margin right', 'quince' ),
        'desc'        => __( 'Move your menu horizontally with this option. Remember to add <code>px</code> value after the number. For example: <code>25px</code>', 'quince' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'default_menu_link',
        'label'       => __( 'Menu link color', 'quince' ),
        'desc'        => __( 'Click input field for color picker or enter your custom value.', 'quince' ),
        'std'         => '#c5cfdd',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'default_menu_link_h',
        'label'       => __( 'Menu link hover color', 'quince' ),
        'desc'        => __( 'Leave empty to use "Theme accent color".', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'menu_hover_bg',
        'label'       => __( 'Menu item background hover color', 'quince' ),
        'desc'        => __( 'Background color for hovered menu item. <br />
Leave empty for transparent black cover with 10% opacity.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'menu_bottom_border',
        'label'       => __( 'Menu bottom border', 'quince' ),
        'desc'        => __( 'Sets 1px bottom border for menu. <br />
Leave empty for no border.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'show_submenu_styles',
        'label'       => __( 'Show submenu styles?', 'quince' ),
        'desc'        => __( 'Enable submenu styling.', 'quince' ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'submenu_background',
        'label'       => __( 'Submenu background color', 'quince' ),
        'desc'        => __( 'Background color for the submenu section. <br />
Leave empty for same color as header.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'show_submenu_styles:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'submenu_link_color',
        'label'       => __( 'Submenu link color', 'quince' ),
        'desc'        => __( 'Color for links in submenu. Leave empty for main menu link color.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'show_submenu_styles:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'submenu_link_hover_color',
        'label'       => __( 'Submenu link hover color', 'quince' ),
        'desc'        => __( 'Hover color for links in megamenu. Leave empty for main menu link color.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'show_submenu_styles:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'megamenu_title_color',
        'label'       => __( 'Submenu title color', 'quince' ),
        'desc'        => __( 'Color for column title inside megamenu.', 'quince' ),
        'std'         => '#fff',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'show_submenu_styles:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'submenu_hover_bg',
        'label'       => __( 'Submenu item background hover color', 'quince' ),
        'desc'        => __( 'Background color for hovered menu item. <br />
Leave empty for transparent black cover with 10% opacity.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'show_submenu_styles:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'current_submenu_bg',
        'label'       => __( 'Active menu item background color', 'quince' ),
        'desc'        => __( 'Background color for hovered submenumenu item. <br />
Leave empty for transparent white cover with 6% opacity.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'show_submenu_styles:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'megamenu_separator_color',
        'label'       => __( 'Megamenu column separator color', 'quince' ),
        'desc'        => __( 'Leave empty for default color.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'show_submenu_styles:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'logo_tab',
        'label'       => __( 'Logo', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'logo',
        'label'       => __( 'Logo', 'quince' ),
        'desc'        => __( 'Please choose an image file for your logo.', 'quince' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'logo_retina',
        'label'       => __( 'Logo (Retina version @2x)', 'quince' ),
        'desc'        => __( 'Retina logo should be <code>2x</code> the size of default logo keeping the aspect ratio!', 'quince' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'retina_logo_width',
        'label'       => __( 'Standart logo width (for retina logo)', 'quince' ),
        'desc'        => __( 'If retina logo is uploaded, please enter the STANDARD (1x) logo width.<br />
Remember to add <code>px</code> value in the end. Example: <code>100px</code>', 'quince' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'retina_logo_height',
        'label'       => __( 'Standart logo height (for retina logo)', 'quince' ),
        'desc'        => __( 'If retina logo is uploaded, please enter the STANDARD (1x) logo height.<br />
Remember to add <code>px</code> value in the end. Example: <code>100px</code>code', 'quince' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'logo_top',
        'label'       => __( 'Margin top', 'quince' ),
        'desc'        => __( 'Move your logo vertically with this option. Remember to add <code>px</code> value after the number. For example: <code>25px</code>px', 'quince' ),
        'std'         => '0px',
        'type'        => 'text',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'logo_left',
        'label'       => __( 'Margin left', 'quince' ),
        'desc'        => __( 'Move your logo horizontally with this option. Remember to add <code>px</code> value after the number. For example: <code>25px</code>', 'quince' ),
        'std'         => '0px',
        'type'        => 'text',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_bar_tab',
        'label'       => __( 'Top bar', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_bar',
        'label'       => __( 'Header top bar', 'quince' ),
        'desc'        => __( 'Top bar appears in header above the menu. If activated, new widget areas appear in Appearance/Widgets - \'Top Bar Sidebar Left\' and \'Top Bar Sidebar Right\'.', 'quince' ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array( 
          array(
            'value'       => 'enable_top_bar',
            'label'       => __( 'Enable Top Bar', 'quince' ),
            'src'         => ''
          )
        )
      ),
      array(
        'id'          => 'top_bar_bg',
        'label'       => __( 'Background color', 'quince' ),
        'desc'        => __( 'Click input field for color picker or enter your custom value.', 'quince' ),
        'std'         => '#2c3e50',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'top_bar:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_bar_text_color',
        'label'       => __( 'Text and link color', 'quince' ),
        'desc'        => __( 'Click input field for color picker or enter your custom value.', 'quince' ),
        'std'         => '#ffffff',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'top_bar:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_bar_link_hover',
        'label'       => __( 'Link hover color', 'quince' ),
        'desc'        => __( 'Click input field for color picker or enter your custom value.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'top_bar:is(on)',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'overlay_header_tab',
        'label'       => __( 'Overlay header', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'overlay_header',
        'label'       => __( 'Overlay header', 'quince' ),
        'desc'        => __( 'Default header style positions above the content.<br /> Overlay header style overlays the content.', 'quince' ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'overlay_header_logo',
        'label'       => __( 'Optional overlay header logo', 'quince' ),
        'desc'        => __( 'Please use the same exact size logo as the original one.', 'quince' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'overlay_header:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'overlay_header_logo_retina',
        'label'       => __( 'Optional overlay header logo (Retina version @2x)', 'quince' ),
        'desc'        => __( 'Retina logo should be <code>2x</code> the size of default logo keeping the aspect ratio!', 'quince' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'overlay_header:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'overlay_header_background',
        'label'       => __( 'Overlay header background (optional)', 'quince' ),
        'desc'        => __( 'Set backgound color for the overlay header.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'overlay_header:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'overlay_header_background_opacity',
        'label'       => __( 'Background color opacity', 'quince' ),
        'desc'        => __( 'Change selected background color opacity. <br />0 = fully transparent and 100 = fully opaque.', 'quince' ),
        'std'         => '30',
        'type'        => 'numeric-slider',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'overlay_header:is(on)',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'overlay_header_background_sticked',
        'label'       => __( 'Overlay header background when sticked & mobile view', 'quince' ),
        'desc'        => __( 'This is the background color of the sticky header when scrolled down. <br/> Same color will be applied to menu in mobile view.', 'quince' ),
        'std'         => '#414856',
        'type'        => 'colorpicker',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'overlay_header:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'overlay_header_pages',
        'label'       =>  __( 'Which page(s) will use overlay header?', 'quince' ),
        'desc'        =>  __( 'Check page(s) where you want overlay header to be active.', 'quince' ),
        'std'         => '',
        'type'        => 'page-checkbox',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'overlay_header:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'title_background_tab',
        'label'       => __( 'Background &amp; colors', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'title_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'title_bg',
        'label'       => __( 'Background', 'quince' ),
        'desc'        => __( 'You can either use color or upload a background image. Leave blank for default setting.', 'quince' ),
        'std'         => '',
        'type'        => 'background',
        'section'     => 'title_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'title_color',
        'label'       => __( 'Title color', 'quince' ),
        'desc'        => __( 'Click input field for color picker or enter your custom value.', 'quince' ),
        'std'         => '#444751',
        'type'        => 'colorpicker',
        'section'     => 'title_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'title_border',
        'label'       => __( 'Border color', 'quince' ),
        'desc'        => __( 'Set 3px wide border color below title area. Leave empty for no border.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'title_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'breadcrumbs_tab',
        'label'       => __( 'Breadcrumbs', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'title_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'breadcrumb',
        'label'       => __( 'Breadcrumbs', 'quince' ),
        'desc'        => __( 'Enable or disable breadcrumbs under the page or post title.', 'quince' ),
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'title_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'breadcrumbs_color',
        'label'       => __( 'Breadcrumb color', 'quince' ),
        'desc'        => __( 'Click input field for color picker or enter your custom value.', 'quince' ),
        'std'         => '#444751',
        'type'        => 'colorpicker',
        'section'     => 'title_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'breadcrumb:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'breadcrumbs_hover_color',
        'label'       => __( 'Breadcrumb hover color', 'quince' ),
        'desc'        => __( 'Click input field for color picker or enter your custom value.', 'quince' ),
        'std'         => '#8fc941',
        'type'        => 'colorpicker',
        'section'     => 'title_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'breadcrumb:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'global_color_section',
        'label'       => __( 'Global', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'body_text_color',
        'label'       => __( 'Body text color', 'quince' ),
        'desc'        => __( 'General color for all body content.', 'quince' ),
        'std'         => '#575757',
        'type'        => 'colorpicker',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'headings_color',
        'label'       => __( 'Headings (H1, H2, H3, H4, H5, H6)', 'quince' ),
        'desc'        => __( 'Color for heading tags. Applies for all heading elements, if different color is not specified in element styling.', 'quince' ),
        'std'         => '#444751',
        'type'        => 'colorpicker',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'link_color',
        'label'       => __( 'Link color', 'quince' ),
        'desc'        => __( 'Global link color.', 'quince' ),
        'std'         => '#999999',
        'type'        => 'colorpicker',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'link_hover_color',
        'label'       => __( 'Link hover color', 'quince' ),
        'desc'        => __( 'Global link hover color. <br /> To use "Theme accent color" leave empty.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'sidebar_tab',
        'label'       => __( 'Sidebar', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'sidebar_text_color',
        'label'       => __( 'Text color', 'quince' ),
        'desc'        => __( 'Choose text color for sidebar widget content.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'sidebar_link_color',
        'label'       => __( 'Link color', 'quince' ),
        'desc'        => __( 'Choose color for links in sidebar.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'sidebar_link_hover_color',
        'label'       => __( 'Link hover color', 'quince' ),
        'desc'        => __( 'Leave empty to use "Theme accent color".', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'sidebar_title_color',
        'label'       => __( 'Widget title color', 'quince' ),
        'desc'        => __( 'Color for widget titles in sidebar.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'sidebar_divider_color',
        'label'       => __( 'Widget divider color', 'quince' ),
        'desc'        => __( 'Choose border line color separating list items in sidebar.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'misc_color_section',
        'label'       => __( 'Misc', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'meta_color',
        'label'       => __( 'Post meta text color', 'quince' ),
        'desc'        => __( 'Set color for post meta fields (tags, date, category, author, comments count) on blog index and single post pages.', 'quince' ),
        'std'         => '#999999',
        'type'        => 'colorpicker',
        'section'     => 'color_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'custom_fonts_tab',
        'label'       => __( 'Custom fonts', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'body_font',
        'label'       => __( 'Body font', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'typography',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'menu_font',
        'label'       => __( 'Menu font', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'typography',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'heading_font',
        'label'       => __( 'Default heading font', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'typography',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'vc_heading_font',
        'label'       => __( 'Visual Composer heading element font', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'typography',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'widget_font',
        'label'       => __( 'Widget title font', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'typography',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'font_size_tab',
        'label'       => __( 'Font sizes', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'body_size',
        'label'       => __( 'Body', 'quince' ),
        'desc'        => __( 'General body font size. <br /> Remember to add <code>px</code> value after the number. For example: <code>13px</code>', 'quince' ),
        'std'         => '14px',
        'type'        => 'text',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'h1',
        'label'       => __( 'H1', 'quince' ),
        'desc'        => __( 'Heading 1 tag font size. <br /> Remember to add <code>px</code> value after the number.', 'quince' ),
        'std'         => '30px',
        'type'        => 'text',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'h2',
        'label'       => __( 'H2', 'quince' ),
        'desc'        => __( 'Heading 2 tag font size. <br />Remember to add <code>px</code> value after the number.', 'quince' ),
        'std'         => '24px',
        'type'        => 'text',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'h3',
        'label'       => __( 'H3', 'quince' ),
        'desc'        => __( 'Heading 3 tag font size. <br />Remember to add <code>px</code> value after the number.', 'quince' ),
        'std'         => '20px',
        'type'        => 'text',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'h4',
        'label'       => __( 'H4', 'quince' ),
        'desc'        => __( 'Heading 4 tag font size. <br />Remember to add <code>px</code> value after the number.', 'quince' ),
        'std'         => '18px',
        'type'        => 'text',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'h5',
        'label'       => __( 'H5', 'quince' ),
        'desc'        => __( 'Heading 5 tag font size. <br />Remember to add <code>px</code> value after the number.', 'quince' ),
        'std'         => '16px',
        'type'        => 'text',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'h6',
        'label'       => __( 'H6', 'quince' ),
        'desc'        => __( 'Heading 6 tag font size. <br />Remember to add <code>px</code> value after the number.', 'quince' ),
        'std'         => '13px',
        'type'        => 'text',
        'section'     => 'typography',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'footer_tab',
        'label'       => __( 'Footer', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'footer_columns',
        'label'       => __( 'Column count', 'quince' ),
        'desc'        => __( 'Choose column count for your footer.', 'quince' ),
        'std'         => 'vc_col-sm-3',
        'type'        => 'select',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array( 
          array(
            'value'       => 'vc_col-sm-12',
            'label'       => __( '1', 'quince' ),
            'src'         => ''
          ),
          array(
            'value'       => 'vc_col-sm-6',
            'label'       => __( '2', 'quince' ),
            'src'         => ''
          ),
          array(
            'value'       => 'vc_col-sm-4',
            'label'       => __( '3', 'quince' ),
            'src'         => ''
          ),
          array(
            'value'       => 'vc_col-sm-3',
            'label'       => __( '4', 'quince' ),
            'src'         => ''
          )
        )
      ),
      array(
        'id'          => 'footer_bg',
        'label'       => __( 'Background', 'quince' ),
        'desc'        => __( 'You can either use color or upload a background image. Leave blank for default setting.', 'quince' ),
        'std'         => '',
        'type'        => 'background',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'footer_text_color',
        'label'       => __( 'Text color', 'quince' ),
        'desc'        => __( 'Choose text color for your footer widget content.', 'quince' ),
        'std'         => '#c5cfdd',
        'type'        => 'colorpicker',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'footer_link',
        'label'       => __( 'Link color', 'quince' ),
        'desc'        => __( 'Will apply color to all links located in footer widgets.', 'quince' ),
        'std'         => '#8690a7',
        'type'        => 'colorpicker',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'footer_link_hover',
        'label'       => __( 'Link hover color', 'quince' ),
        'desc'        => __( 'Leave empty to use "Theme accent color".', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'footer_widget_title',
        'label'       => __( 'Widget title color', 'quince' ),
        'desc'        => __( 'Color for widget titles in footer.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'copyright_tab',
        'label'       => __( 'Copyright', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'copyright_bg',
        'label'       => __( 'Background', 'quince' ),
        'desc'        => __( 'You can either use color or upload a background image. Leave blank for default setting.', 'quince' ),
        'std'         => '',
        'type'        => 'background',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'copyright_text_color',
        'label'       => __( 'Text color', 'quince' ),
        'desc'        => __( 'Choose text color for your copyright area widget content.', 'quince' ),
        'std'         => '#8690a7',
        'type'        => 'colorpicker',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'copyright_link',
        'label'       => __( 'Link color', 'quince' ),
        'desc'        => __( 'Color for links located in your copyright area widgets.', 'quince' ),
        'std'         => '#c5cfdd',
        'type'        => 'colorpicker',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'copyright_link_hover',
        'label'       => __( 'Link hover color', 'quince' ),
        'desc'        => __( 'Leave empty to use "Theme accent color".', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'copyright_widget_title',
        'label'       => __( 'Widget title color', 'quince' ),
        'desc'        => __( 'Color for widget titles in copyright area.', 'quince' ),
        'std'         => '',
        'type'        => 'colorpicker',
        'section'     => 'footer_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'blog_tab',
        'label'       => __( 'Blog', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'blog_layout',
        'label'       => __( 'Blog layout', 'quince' ),
        'desc'        => __( '1. Full width content<br />
2. Content / Right sidebar <br />
3. Content / Left sidebar', 'quince' ),
        'std'         => 'right-sidebar',
        'type'        => 'radio-image',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'blog_post_text_align',
        'label'       => __( 'Blog post text align', 'quince' ),
        'desc'        => __( 'Choose text align for the blog post.', 'quince' ),
        'std'         => 'left',
        'type'        => 'select',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array( 
          array(
            'value'       => 'left',
            'label'       => __( 'Left', 'quince' ),
            'src'         => ''
          ),
          array(
            'value'       => 'center',
            'label'       => __( 'Center', 'quince' ),
            'src'         => ''
          ),
          array(
            'value'       => 'right',
            'label'       => __( 'Right', 'quince' ),
            'src'         => ''
          )
        )
      ),
      array(
        'id'          => 'blog_title',
        'label'       => __( 'Blog title', 'quince' ),
        'desc'        => __( 'Choose whether to display or hide blog title.', 'quince' ),
        'std'         => '',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'blog_custom_header',
        'label'       => __( 'Custom HTML after header in blog page', 'quince' ),
        'desc'        => __( 'Insert any custom code you wish. Shortcodes allowed!', 'quince' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'content_type',
        'label'       => __( 'Content type for post preview', 'quince' ),
        'desc'        => __( 'Choose what to display on blog index pages. Note that only \'Full Content\' respects WordPress \'read more\' tag.', 'quince' ),
        'std'         => 'excerpt',
        'type'        => 'select',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array( 
          array(
            'value'       => 'excerpt',
            'label'       => __( 'Excerpt', 'quince' ),
            'src'         => ''
          ),
          array(
            'value'       => 'full_content',
            'label'       => __( 'Full content', 'quince' ),
            'src'         => ''
          )
        )
      ),
      array(
        'id'          => 'exclude_from_blog',
        'label'       => __( 'Exclude category from blog', 'quince' ),
        'desc'        => __( 'This option will exclude selected category posts from blog and search pages.', 'quince' ),
        'std'         => '',
        'type'        => 'category-checkbox',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'post_date',
        'label'       => __( 'Post date in meta', 'quince' ),
        'desc'        => __( 'Do you want to display date in post meta fields?', 'quince' ),
        'std'         => '',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'post_category',
        'label'       => __( 'Post category in meta', 'quince' ),
        'desc'        => __( 'Do you want to display category in post meta fields?', 'quince' ),
        'std'         => '',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'post_author',
        'label'       => __( 'Post author in meta', 'quince' ),
        'desc'        => __( 'Do you want to display author in post meta fields?', 'quince' ),
        'std'         => '',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'post_comments',
        'label'       => __( 'Comments link in meta', 'quince' ),
        'desc'        => __( 'Do you want to display comment count in post meta fields?', 'quince' ),
        'std'         => '',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'post_tab',
        'label'       => __( 'Posts', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'tab',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'post_layout',
        'label'       => __( 'Post layout', 'quince' ),
        'desc'        => __( '1. Full width content<br />
2. Content / Right sidebar <br />
3. Content / Left sidebar', 'quince' ),
        'std'         => 'right-sidebar',
        'type'        => 'radio-image',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'single_post_text_align',
        'label'       => __( 'Post text align', 'quince' ),
        'desc'        => __( 'Choose text align for single post.', 'quince' ),
        'std'         => 'left',
        'type'        => 'select',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array( 
          array(
            'value'       => 'left',
            'label'       => __( 'Left', 'quince' ),
            'src'         => ''
          ),
          array(
            'value'       => 'center',
            'label'       => __( 'Center', 'quince' ),
            'src'         => ''
          ),
          array(
            'value'       => 'right',
            'label'       => __( 'Right', 'quince' ),
            'src'         => ''
          )
        )
      ),
      array(
        'id'          => 'post_links',
        'label'       => __( 'Previous &amp; next post link', 'quince' ),
        'desc'        => __( 'Do you want to display next and previous post links on single blog post page?', 'quince' ),
        'std'         => '',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'post_tags',
        'label'       => __( 'Post tags after content', 'quince' ),
        'desc'        => __( 'Display post tags on single post page?', 'quince' ),
        'std'         => '',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'author_description',
        'label'       => __( 'Post author description', 'quince' ),
        'desc'        => __( 'When ON, author info box will only appear for those post authors who have "Biographical Info" field filled!', 'quince' ),
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'cart_widget',
        'label'       => __( 'Display cart content on hover', 'quince' ),
        'desc'        => __( 'Display cart content on icon hover (ON) or just lead to cart page on click (OFF)?', 'quince' ),
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'woocommerce',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'cart_button:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'catalog_layout',
        'label'       => __( 'Product archive page (shop) layout', 'quince' ),
        'desc'        => __( '1. Full width content<br />
2. Content / Right sidebar <br />
3. Content / Left sidebar', 'quince' ),
        'std'         => 'right-sidebar',
        'type'        => 'radio-image',
        'section'     => 'woocommerce',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'woo_title',
        'label'       => __( 'WooCommerce product page title', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'on-off',
        'section'     => 'woocommerce',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'woo_custom_header',
        'label'       => __( 'Custom HTML after header in WooCommerce product page', 'quince' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'woocommerce',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'product_layout',
        'label'       => __( 'Single product page layout', 'quince' ),
        'desc'        => __( '1. Full width content<br />
2. Content / Right sidebar <br />
3. Content / Left sidebar', 'quince' ),
        'std'         => 'right-sidebar',
        'type'        => 'radio-image',
        'section'     => 'woocommerce',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'woo_columns',
        'label'       => __( 'Product column count', 'quince' ),
        'desc'        => __( 'Choose column count for main product catalog page.', 'quince' ),
        'std'         => '',
        'type'        => 'select',
        'section'     => 'woocommerce',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array( 
          array(
            'value'       => '3',
            'label'       => __( '3 columns', 'quince' ),
            'src'         => ''
          ),
          array(
            'value'       => '4',
            'label'       => __( '4 columns', 'quince' ),
            'src'         => ''
          )
        )
      ),
      array(
        'id'          => 'woo_product_count',
        'label'       => __( 'Products per page', 'quince' ),
        'desc'        => __( 'Choose how many products to display on product catalog page.', 'quince' ),
        'std'         => '9',
        'type'        => 'text',
        'section'     => 'woocommerce',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'custom_css',
        'label'       => __( 'Custom CSS', 'quince' ),
        'desc'        => __( 'Add any of your custom CSS here: <br /> 

<pre><code>.page-id-10 #site-header {
background:none;
}
</code></pre>

Have fun!', 'quince' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'custom_css',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'import_demo_data_section',
        'label'       => __( 'Import demo', 'quince' ),
        'desc'        => __( '<h1>Welcome to Quince!</h1>
<span class="import_note">You can replicate live preview website by importing demo data.<br /> Posts, pages, widgets, menus and reading settings will be set automatically. <br />You can change and edit everything later.</span>

<a href="themes.php?page=ot-theme-options&amp;import_data_content=true">Import demo data</a>

<span class="import_note import_warning"><strong>NOTICE: </strong>Images and graphics used in live demo are licensed for preview purposes only and are replaced with placeholder images in this demo content.</span>', 'quince' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'import_data',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'import-demo',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'import_successful_section',
        'label'       => __( 'Import successful', 'quince' ),
        'desc'        => __( '<div class="success-icon"></div>
<h1>Data Imported Successfully!</h1>', 'quince' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'import_successful',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'import-successful',
        'condition'   => '',
        'operator'    => 'and'
      )
    )
  );
  
  /* allow settings to be filtered before saving */
  $custom_settings = apply_filters( ot_settings_id() . '_args', $custom_settings );
  
  /* settings are not the same update the DB */
  if ( $saved_settings !== $custom_settings ) {
    update_option( ot_settings_id(), $custom_settings ); 
  }
  
  /* Lets OptionTree know the UI Builder is being overridden */
  global $ot_has_custom_theme_options;
  $ot_has_custom_theme_options = true;
  
}